name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate Docker with GCR
        run: echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build Docker Image
        run: docker build -t gcr.io/cloud-native-ecommerce-jfields/cloud-native-ecommerce:latest .

      - name: Push Docker Image to GCR
        run: docker push gcr.io/cloud-native-ecommerce-jfields/cloud-native-ecommerce:latest

      - name: Configure Gcloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project cloud-native-ecommerce-jfields

      - name: Configure Kubectl
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: True
        run: |
          gcloud container clusters get-credentials flask-gke-cluster --region us-central1

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/flask-app
          kubectl get pods
          kubectl get svc

      - name: Cleanup Gcloud Key File
        run: rm -f $HOME/gcp-key.json
